{
    "openapi" : "3.0.0",
    "info" : {
        "title" : "API de gerenciamento de uma loja de carros",
        "description" : "Essa API tem como objetivo o gerenciamento de uma loja de carros, com manipulação de usuários e produtos",
        "contact" : {
            "email" : "leonardo.pin.s2002@gmail.com"
        },
        "version" : "1.0.0"
    },
    "servers" : [
        {
            "url" : "http://localhost:8081",
            "description" : "API de testes"
        }
    ],
    "paths" : {
        "/login" : {
            "post" : {
                "sumary" : "Logar no sistema",
                "description" : "Rota na qual o usuário não logado pode realizar seu login para acessar as funcionalidades do sistema disponíveis para seu nível de acesso",
                "tags" : ["Usuario"],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/Admin"
                            },
                            "examples" : {
                                "login" : {
                                    "value" : {
                                        "cpf" : "78945612301",
                                        "password" : "123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "properties" : {
                                        "user" : {
                                            "type" : "object",
                                            "$ref" : "#/components/schemas/Usuario"
                                        },
                                        "token" : {
                                            "type" : "string"
                                        }
                                    }
                                }
                            }
                        }
                     }
                } 
            }
        },

        "/carros" : {
            "get" : {
                "sumary" : "Visualizar carros",
                "description" : "Rota pública responsável por mostrar os carros cadastrados no sistema",
                "tags" : ["Carros"],
                "responses": {
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "array",
                                    "items" : {
                                        "$ref" : "#/components/schemas/Carro"
                                    }
                                }
                            }
                        }
                    },
                    "204" : {
                        "description" : "No Content"
                    },
                    "500" : {
                        "description" : "Internal Error"
                    }
                }
            }
        },

        "/carros/{chassis}" : {
            "get" : {
                "sumary" : "Visualizar carro específico",
                "description" : "Rota pública responsável por mostrar as informações de um carro especificado nas params",
                "tags" : ["Carros"],
                "parameters" : [
                    {
                        "name" : "chassis",
                        "in" : "path",
                        "description" : "Chassi do carro para buscá-lo no sistema",
                        "required" : true
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Carro"
                                }
                            }
                        }
                    },
                    "204" : {
                        "description" : "No Content"
                    },
                    "500" : {
                        "description" : "Internal Error"
                    },
                    "400" : {
                        "description" : "Bad Request"
                    }
                }
            }
        },

        "/usuario/carros" : {
            "get" : {
                "sumary" : "Visualizar carros",
                "description" : "Rota responsável por mostrar os carros cadastrados no sistema, com dados internos",
                "tags" : ["Carros"],
                "security" : [{"bearerAuth" : []}],
                "responses": {
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "array",
                                    "items" : {
                                        "$ref" : "#/components/schemas/Carro"
                                    }
                                }
                            }
                        }
                    },
                    "204" : {
                        "description" : "No Content"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    },
                    "500" : {
                        "description" : "Internal Error"
                    }
                }
            }
        },

        "/usuario/carros/{chassis}" : {
            "get" : {
                "sumary" : "Visualizar carro específico",
                "description" : "Rota responsável por mostrar as informações de um carro especificado nas params",
                "tags" : ["Carros"],
                "security" : [{"bearerAuth" : []}],
                "parameters" : [
                    {
                        "name" : "chassis",
                        "in" : "path",
                        "description" : "Chassi do carro para buscá-lo no sistema",
                        "required" : true
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Carro"
                                }
                            }
                        }
                    },
                    "500" : {
                        "description" : "Internal Error"
                    },
                    "400" : {
                        "description" : "Bad Request"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
                }
            }
        },

        "/usuario/editar" : {
            "put" : {
                "sumary" : "Editar usuário",
                "description" : "Rota na qual o usuário logado pode modificar alguns dados da sua conta",
                "tags" : ["Usuario"],
                "security" : [{"bearerAuth" : []}],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/Usuario"
                            },
                            "examples" : {
                                "usuario" : {
                                    "value" : {
                                        "name" : "Joao Editado",
                                        "biography" : "Olá! tenho 22 anos e sou dev backend"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Usuario"
                                }
                            }
                        }
                     }
                } 
            }
        },

        "/usuario/avatar" : {
            "post": {
                "sumary" : "Avatar do usuário",
                "description" : "Rota na qual o usuário logado pode adicionar um avatar para a sua conta",
                "tags" : ["Usuario"],
                "security" : [{"bearerAuth" : []}],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema":{
                                "type": "object",
                                "properties":{
                                    "file": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401" : {
                        "description" : "Unauthorized"
                     },
                     "400" : {
                         "description" : "Bad Request"
                      },
                      "500" : {
                         "description" : "Internal Error"
                      },
                      "200" : {
                         "description" : "OK",
                         "content" : {
                             "application/json" : {
                                 "schema" : {
                                     "type" : "object",
                                     "$ref" : "#/components/schemas/Avatar"
                                 }
                             }
                         }
                      }
                }
            }
        },

        "/usuario/minha-conta" : {
            "get" : {
                "sumary" : "Visualizar usuário",
                "description" : "Rota na qual o usuário logado pode acessar os dados da sua conta",
                "tags" : ["Usuario"],
                "security" : [{"bearerAuth" : []}],
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Usuario"
                                }
                            }
                        }
                     }
                } 
            }
        },
        
        "/usuario/minhas-vendas" : {
            "get" : {
                "sumary" : "Visualizar vendas do usuário",
                "description" : "Rota na qual o usuário logado pode acessar os registros de suas vendas",
                "tags" : ["Usuario"],
                "security" : [{"bearerAuth" : []}],
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Usuario"
                                }
                            }
                        }
                     }
                } 
            }
        },

        "/usuario/vender/{chassis}" : {
            "post" : {
                "sumary" : "Realizar uma venda",
                "description" : "Rota na qual o usuário pode registrar uma venda",
                "tags" : ["Vendas"],
                "security" : [{"bearerAuth" : []}],
                "parameters" : [
                    {
                        "name" : "chassis",
                        "in" : "path",
                        "description" : "Chassi do carro para buscá-lo no sistema",
                        "required" : true
                    }
                ],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/Venda"
                            },
                            "examples" : {
                                "usuario" : {
                                    "value" : {
                                        "sold" : false,
                                        "reserved" : true,
                                        "sell_price" : "",
                                        "client_cpf" : "98765431011"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Usuario"
                                }
                            }
                        }
                     }
                } 
            },

            "put" : {
                "sumary" : "Realizar uma venda em um carro reservado",
                "description" : "Rota na qual o usuário pode registrar uma venda através de uma reserva feita anteriormente",
                "tags" : ["Vendas"],
                "security" : [{"bearerAuth" : []}],
                "parameters" : [
                    {
                        "name" : "chassis",
                        "in" : "path",
                        "description" : "Chassi do carro para buscá-lo no sistema",
                        "required" : true
                    }
                ],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/Venda"
                            },
                            "examples" : {
                                "usuario" : {
                                    "value" : {
                                        "sold" : true,
                                        "sell_price" : "60000"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Usuario"
                                }
                            }
                        }
                     }
                } 
            }
        },

        "/admin/cadastrar" : {
            "post" : {
                "sumary" : "Cadastrar novos usuários",
                "description" : "Rota na qual o usuário administrador pode cadastrar novos usuários no sistema. Obs: o cpf e o email devem ser únicos",
                "tags" : ["Admin"],
                "security" : [{"bearerAuth" : []}],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/Usuario"
                            },
                            "examples" : {
                                "usuario" : {
                                    "value" : {
                                        "name" : "Joao",
                                        "cpf" : "78945612301",
                                        "email" : "joao@email.example.com",
                                        "biography" : "Olá! tenho 22 anos e sou dev",
                                        "password" : "123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Usuario"
                                }
                            }
                        }
                     }
                } 
            }
        },
        
        "/admin/cadastrar/admin" : {
            "post" : {
                "sumary" : "Cadastrar novos usuários",
                "description" : "Rota na qual o usuário administrador pode cadastrar novos usuários no sistema. Obs: o cpf e o email devem ser únicos",
                "tags" : ["Admin"],
                "security" : [{"bearerAuth" : []}],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/Admin"
                            },
                            "examples" : {
                                "usuario" : {
                                    "value" : {
                                        "cpf" : "78945612301"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "201" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Admin"
                                }
                            }
                        }
                     }
                } 
            }
        },
        
        "/admin/administradores" : {
            "get" : {
                "sumary" : "Visualizar administradores",
                "description" : "Rota responsável por listar os usuários administradores do sistema",
                "tags" : ["Admin"],
                "security" : [{"bearerAuth" : []}],
                "responses": {
                    "401" : {
                        "description" : "Unauthorized"
                     },
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "array",
                                    "items" : {
                                        "$ref" : "#/components/schemas/Usuario"
                                    }
                                }
                            }
                        }
                    },
                    "204" : {
                        "description" : "No Content"
                    },
                    "500" : {
                        "description" : "Internal Error"
                    }
                }
            }
        },

        "/admin/usuarios" : {
            "get" : {
                "sumary" : "Visualizar usuários",
                "description" : "Rota responsável por listar todos os usuários do sistema",
                "tags" : ["Admin"],
                "security" : [{"bearerAuth" : []}],
                "responses": {
                    "401" : {
                        "description" : "Unauthorized"
                     },
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "array",
                                    "items" : {
                                        "$ref" : "#/components/schemas/Usuario"
                                    }
                                }
                            }
                        }
                    },
                    "204" : {
                        "description" : "No Content"
                    },
                    "500" : {
                        "description" : "Internal Error"
                    }
                }
            }
        },

        "/admin/carros/cadastrar" : {
            "post" : {
                "sumary" : "Cadastrar novos carros",
                "description" : "Rota na qual o usuário administrador pode cadastrar novos carros no sistema.",
                "tags" : ["Admin"],
                "security" : [{"bearerAuth" : []}],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/Carro"
                            },
                            "examples" : {
                                "usuario" : {
                                    "value" : {
                                        "brand" : "Aston Martin",
                                        "model" : "Grã turismo",
                                        "chassis" : "007",
                                        "year" : "1963",
                                        "km" : "007",
                                        "color" : "cinza",
                                        "buy_price" : "9999999"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "201" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Carro"
                                }
                            }
                        }
                     }
                } 
            }
        },

        "/admin/carros/editar/{chassis}" : {
            "put" : {
                "sumary" : "Editar carro",
                "description" : "Rota na qual o usuário administrador pode alterar os dados de um carro cadastrado no sistema",
                "tags" : ["Admin"],
                "security" : [{"bearerAuth" : []}],
                "parameters" : [
                    {
                        "name" : "chassis",
                        "in" : "path",
                        "description" : "Chassi do carro para buscá-lo no sistema",
                        "required" : true
                    }
                ],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/Carro"
                            },
                            "examples" : {
                                "usuario" : {
                                    "value" : {
                                        "model" : "Grã turismo - luxo",
                                        "color" : "prata metálico"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "$ref" : "#/components/schemas/Carro"
                                }
                            }
                        }
                     }
                } 
            }
        },

        "/admin/deletar/usuario" : {
            "delete" : {
                "sumary" : "Deletar um usuário",
                "description" : "Rota na qual o usuário administrador pode deletar um usuário do sistema. Obs: o admin deverá preencher com a sua senha e com o cpf do usuário que deseja apagar",
                "tags" : ["Admin"],
                "security" : [{"bearerAuth" : []}],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "userCpf" : "string",
                                    "password" : "string"
                                }
                            },
                            "examples" : {
                                "data" : {
                                    "value" : {
                                        "userCpf" : "78945612301",
                                        "password" : ""
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "401" : {
                       "description" : "Unauthorized"
                    },
                    "400" : {
                        "description" : "Bad Request"
                     },
                     "500" : {
                        "description" : "Internal Error"
                     },
                     "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "properties" : {
                                        "text" : "user deleted!"
                                    }
                                }
                            }
                        }
                     }
                }
            }
        },

        "/admin/carros/deletar/{chassis}" : {
            "delete" : {
                "delete" : {
                    "sumary" : "Deletar um carro",
                    "description" : "Rota na qual o usuário administrador pode deletar um usuário do sistema. Obs: o admin deverá preencher com a sua senha e com o cpf do usuário que deseja apagar",
                    "tags" : ["Admin"],
                    "security" : [{"bearerAuth" : []}],
                    "parameters" : [
                        {
                            "name" : "chassis",
                            "in" : "path",
                            "description" : "Chassi do carro para buscá-lo no sistema",
                            "required" : true
                        }
                    ],
                    "responses" : {
                        "401" : {
                           "description" : "Unauthorized"
                        },
                        "400" : {
                            "description" : "Bad Request"
                         },
                         "500" : {
                            "description" : "Internal Error"
                         },
                         "204" : {
                            "description" : "No Content"
                         }
                    }
                }
            }
        }
    },

    "components" : {
        "schemas" : {
            "Usuario" : {
                "type" : "object",
                "properties" : {
                    "name" : {
                        "type" : "string"
                    },
                    "cpf" : {
                        "type" : "string"
                    },
                    "email" : {
                        "type" : "string"
                    },
                    "biography" : {
                        "type" : "string"
                    },
                    "password" : {
                        "type" : "string"
                    }
                }
            },
            "Admin" : {
                "type" : "object",
                "properties" : {
                    "user_id" : {
                        "type" : "string"
                    }
                }
            },
            "Carro" : {
                "type" : "object",
                "properties" : {
                    "brand" : {
                        "type" : "string"
                    },
                    "model" : {
                        "type" : "string"
                    },
                    "chassis" : {
                        "type" : "string"
                    },
                    "year" : {
                        "type" : "string"
                    },
                    "km" : {
                        "type" : "string"
                    },
                    "color" : {
                        "type" : "string"
                    },
                    "buy_price" : {
                        "type" : "string"
                    }
                }
            },
            "Venda" : {
                "type" : "object",
                "properties" : {
                    "user_id" : {
                        "type" : "string"
                    },
                    "car_chassis" : {
                        "type" : "string"
                    },
                    "sold" : {
                        "type" : "boolean"
                    },
                    "reserved" : {
                        "type" : "boolean"
                    },
                    "sell_price" : {
                        "type" : "string"
                    },
                    "client_cpf" : {
                        "type" : "string"
                    }
                }
            },
            "Avatar" : {
                "type": "object",
                "properties":{
                    "file": {
                        "type": "string",
                        "format": "binary"
                    }
                }
            }
        },
        "securitySchemes" : {
            "bearerAuth" : {
                "type" : "http",
                "scheme" : "bearer",
                "bearerFormat" : "JWT"
            }
        }
    }
}